export enum IconEnum {
    Data = 'data',
    Delete = 'delete',
    Edit = 'edit',
    Home = 'home',
    Info = 'info',
    Key = 'key',
    New = 'new',
    Refresh = 'refresh',
    Settings = 'settings',
    System = 'system',
    User = 'user',

    // NEW ICONS
    Send = 'send',
    Export = 'export',
    Generate = 'generate',
    QrCode = 'qrcode',
    Action = 'action',
    Notifications = 'notifications',
    Search = 'search',
    Save = 'save',
    OpenFile = 'openfile',
    OpenFolder = 'openfolder',
    FilePDF = 'filepdf',
    FileExcel = 'fileexcel',
    FileCSV = 'filecsv',
    Mobile = 'mobile',
    Play = 'play',
    Pause = 'pause',
    Stop = 'stop',
    Upload = 'upload',
    Attach = 'attach',
    OpenLink = 'openlink'
}
